export interface ServiceData {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  overview: string;
  whatToExpect: string[];
  recovery: string;
  faqs: { question: string; answer: string }[];
  metaTitle: string;
  metaDescription: string;
}

export const services: ServiceData[] = [
  {
    slug: "root-canal",
    shortTitle: "Root Canal",
    title: "Root Canal Treatment",
    description: "As a tooth gets grossly decayed, the pulp gets infected — triggering intense pain. Dr. Vivek's specialist endodontic training ensures painless, precision root canal therapy that saves your natural teeth.",
    overview: "Root canal treatment removes infected pulp from inside your tooth, relieving pain and preserving the natural structure. As a tooth gets grossly decayed the pulp of the tooth gets infected, either damaging it or exposing it, which triggers intense pain. Pain and sensitivity are two different terms — and Dr. Vivek, with his MDS in Conservative Dentistry & Endodontics, brings specialist-level expertise to accurately diagnose and treat every case using rotary instruments and apex locators for predictable, comfortable outcomes.",
    whatToExpect: [
      "Thorough diagnosis with digital X-rays",
      "Local anesthesia for a completely painless experience",
      "Precise cleaning and shaping of root canals",
      "Biocompatible filling and sealing",
      "Crown placement for long-term protection",
    ],
    recovery: "Most patients return to normal activities the same day. Mild sensitivity for 2-3 days is normal and managed with over-the-counter medication.",
    faqs: [
      { question: "Is root canal treatment painful?", answer: "With modern anesthesia and Dr. Vivek's gentle technique, the procedure is virtually painless. Most patients compare it to getting a routine filling." },
      { question: "How many visits does it take?", answer: "Most root canals are completed in 1-2 visits, each lasting 45-60 minutes." },
      { question: "How long does a root canal last?", answer: "With proper crown placement and oral hygiene, a root canal treated tooth can last a lifetime." },
      { question: "What is the cost of root canal in Hyderabad?", answer: "Costs vary based on the tooth and complexity. We provide transparent pricing during your consultation — no hidden fees." },
    ],
    metaTitle: "Root Canal Treatment in Hyderabad — Vivek Dental",
    metaDescription: "Painless root canal by MDS Endodontics specialist Dr. Vivek in Vengal Rao Nagar, Hyderabad. Advanced techniques, same-day relief. Book now.",
  },
  {
    slug: "smile-designing",
    shortTitle: "Smile Design",
    title: "Smile Designing & Cosmetic Dentistry",
    description: "A face is said beautiful when it has a beautiful smile. A smile is mostly dependent on the teeth — the way they are present or aligned in our mouth. Transform yours with expert cosmetic dentistry.",
    overview: "A face is said beautiful when it has a beautiful smile. A smile is mostly dependent on the teeth — the way they are present or aligned in our mouth. To make your smile beautiful, Dr. Vivek combines art and dental science using digital planning and high-quality materials like porcelain veneers and composite bonding to design smiles that look natural and enhance your confidence. Every smile makeover is customized to complement your unique facial features.",
    whatToExpect: [
      "Digital smile analysis and mockup",
      "Discussion of goals and treatment options",
      "Minimally invasive preparation",
      "Custom-fabricated veneers or bonding",
      "Final placement and adjustments",
    ],
    recovery: "Veneers require no downtime. Composite bonding is completed in a single visit. You'll leave with your new smile the same day in many cases.",
    faqs: [
      { question: "What is smile designing?", answer: "It's a customized treatment plan combining cosmetic procedures — veneers, bonding, whitening, and alignment — to create your ideal smile." },
      { question: "How long do veneers last?", answer: "Porcelain veneers typically last 10-15 years with proper care." },
      { question: "Is it painful?", answer: "Most smile design procedures involve minimal to no discomfort. Local anesthesia is used when needed." },
    ],
    metaTitle: "Smile Designing in Hyderabad — Vivek Dental",
    metaDescription: "Expert cosmetic dentistry and smile makeover in Hyderabad by Dr. Vivek. Veneers, bonding & digital smile design. Natural-looking results.",
  },
  {
    slug: "tooth-whitening",
    shortTitle: "Whitening",
    title: "Professional Tooth Whitening",
    description: "Looking to enhance the brightness of your teeth? Whitening or bleaching is the absolute solution. Tooth whitening lightens teeth and helps to remove stains and discoloration.",
    overview: "Looking to enhance the brightness of your teeth? Whitening or bleaching is the absolute solution. Tooth whitening lightens teeth and helps to remove stains and discoloration. Professional whitening at Vivek Dental uses clinically proven bleaching agents that are far more effective and safer than over-the-counter products. The treatment is supervised by Dr. Vivek to ensure even results without sensitivity — achieving up to 8 shades brighter in a single session.",
    whatToExpect: [
      "Dental examination and shade assessment",
      "Gum protection application",
      "Professional-grade whitening gel application",
      "Light activation for enhanced results",
      "Post-treatment care instructions",
    ],
    recovery: "You can eat and drink normally within a few hours. Minor sensitivity may occur for 24-48 hours.",
    faqs: [
      { question: "How white will my teeth get?", answer: "Most patients achieve 4-8 shades of improvement in a single session." },
      { question: "Is professional whitening safe?", answer: "Yes, when performed by a qualified dentist, it's completely safe for your enamel." },
      { question: "How long do results last?", answer: "Results last 6-12 months depending on diet and habits. Touch-up treatments can maintain brightness." },
    ],
    metaTitle: "Teeth Whitening in Hyderabad — Vivek Dental",
    metaDescription: "Professional teeth whitening in Hyderabad. Up to 8 shades brighter in one visit. Safe, effective treatment by Dr. Vivek. Book today.",
  },
  {
    slug: "dental-implants",
    shortTitle: "Implants",
    title: "Dental Implants",
    description: "Permanent tooth replacement with titanium implants — the gold standard for missing teeth restoration. Function and feel exactly like real teeth.",
    overview: "Dental implants are titanium posts surgically placed in the jawbone that serve as artificial tooth roots. Topped with natural-looking crowns, they function and feel exactly like real teeth. Dr. Vivek works with premium implant systems for predictable, long-lasting results that restore both your confidence and your ability to chew comfortably.",
    whatToExpect: [
      "Comprehensive evaluation with 3D imaging",
      "Implant placement under local anesthesia",
      "Healing period of 3-6 months for integration",
      "Abutment and custom crown placement",
      "Follow-up care and maintenance guidance",
    ],
    recovery: "Initial healing takes 1-2 weeks. Full osseointegration (bone fusion) takes 3-6 months, during which you'll have a temporary restoration.",
    faqs: [
      { question: "Am I a candidate for implants?", answer: "Most adults with good general health and adequate jawbone are candidates. A consultation with imaging will confirm." },
      { question: "How long do implants last?", answer: "With proper care, dental implants can last a lifetime. The crown may need replacement every 10-15 years." },
      { question: "Is the procedure painful?", answer: "The procedure is performed under local anesthesia and is well-tolerated. Post-operative discomfort is manageable with medication." },
    ],
    metaTitle: "Dental Implants in Hyderabad — Vivek Dental",
    metaDescription: "Premium dental implants in Hyderabad by Dr. Vivek. Permanent, natural-looking tooth replacement. Expert care in Vengal Rao Nagar.",
  },
  {
    slug: "orthodontics",
    shortTitle: "Braces & Aligners",
    title: "Orthodontics & Dental Braces",
    description: "Straight teeth and a perfect bite with modern braces, ceramic braces, and clear aligners — expert dental braces fixing for children and adults.",
    overview: "Orthodontic treatment at Vivek Dental corrects misaligned teeth and jaw issues using traditional braces, ceramic braces, or clear aligners. Dr. Vivek provides expert dental braces fixing with personalized treatment plans to achieve optimal alignment, a beautiful smile, and improved oral health for patients of all ages.",
    whatToExpect: [
      "Detailed orthodontic assessment and records",
      "Custom treatment plan with timeline",
      "Braces or aligner fitting",
      "Regular adjustment appointments",
      "Retainer fitting after treatment completion",
    ],
    recovery: "Mild discomfort for 2-3 days after each adjustment is normal. Treatment typically takes 12-24 months depending on complexity.",
    faqs: [
      { question: "What age is best for braces?", answer: "While ideal for teens, orthodontic treatment is effective at any age. Many of our patients are adults." },
      { question: "Can I get clear/invisible braces?", answer: "Yes, we offer ceramic braces and clear aligner options for a discreet treatment experience." },
      { question: "How long does treatment take?", answer: "Typically 12-24 months, though minor corrections may take as little as 6 months." },
    ],
    metaTitle: "Orthodontics & Braces in Hyderabad — Vivek Dental",
    metaDescription: "Expert orthodontic treatment in Hyderabad. Braces, ceramic braces & clear aligners for all ages. Straight teeth by Dr. Vivek.",
  },
  {
    slug: "oral-surgery",
    shortTitle: "Oral Surgery",
    title: "Oral Surgery",
    description: "Expert surgical procedures including wisdom tooth extraction, cyst removal, and pre-prosthetic surgery — performed with precision and gentle care.",
    overview: "Oral surgery at Vivek Dental covers a range of surgical procedures performed with precision and care. From complex extractions to cyst removals, Dr. Vivek ensures every procedure is performed safely with minimal discomfort using advanced surgical protocols and appropriate anesthesia.",
    whatToExpect: [
      "Thorough evaluation and treatment planning",
      "Pre-operative instructions and preparation",
      "Surgery under appropriate anesthesia",
      "Post-operative care and medication",
      "Follow-up visits for healing assessment",
    ],
    recovery: "Recovery varies by procedure — most patients recover within 3-7 days. Detailed post-operative care instructions are provided.",
    faqs: [
      { question: "When is wisdom tooth removal necessary?", answer: "When wisdom teeth are impacted, causing pain, infection, or crowding of other teeth." },
      { question: "Is oral surgery safe?", answer: "Yes, when performed by a qualified specialist with proper planning and modern techniques." },
      { question: "What anesthesia is used?", answer: "Local anesthesia is standard. Sedation options are available for anxious patients." },
    ],
    metaTitle: "Oral Surgery in Hyderabad — Vivek Dental",
    metaDescription: "Expert oral surgery in Hyderabad. Wisdom tooth extraction, cyst removal & more by Dr. Vivek. Safe, precise procedures.",
  },
  {
    slug: "veneers-laminates",
    shortTitle: "Veneers & Laminates",
    title: "Veneers & Laminates",
    description: "Ultra-thin porcelain or composite shells bonded to the front of your teeth — instantly correcting chips, gaps, stains, and uneven teeth.",
    overview: "Dental veneers and laminates are wafer-thin, custom-made shells designed to cover the front surface of teeth. They are an excellent solution for correcting chipped, stained, misaligned, or irregularly shaped teeth. Dr. Vivek uses premium porcelain and composite materials to create veneers that mimic the light-reflecting properties of natural teeth for a flawless, natural-looking result.",
    whatToExpect: [
      "Consultation and shade matching",
      "Minimal tooth preparation (0.3–0.5mm)",
      "Impressions for custom fabrication",
      "Trial placement and adjustments",
      "Permanent bonding and polishing",
    ],
    recovery: "No downtime required. You can resume normal activities immediately. Avoid biting hard objects for the first 48 hours.",
    faqs: [
      { question: "What's the difference between veneers and laminates?", answer: "Laminates are ultra-thin (no-prep or minimal-prep) veneers. Both achieve similar cosmetic results — the choice depends on your specific needs." },
      { question: "Do veneers damage natural teeth?", answer: "Modern veneers require minimal preparation. Dr. Vivek uses conservative techniques to preserve maximum tooth structure." },
      { question: "Can veneers fix crooked teeth?", answer: "Yes, veneers can create the appearance of perfectly aligned teeth without braces for mild to moderate cases." },
    ],
    metaTitle: "Dental Veneers & Laminates in Hyderabad — Vivek Dental",
    metaDescription: "Custom porcelain veneers and laminates in Hyderabad. Fix chips, gaps, and stains instantly. Natural results by Dr. Vivek.",
  },
  {
    slug: "dental-fillings",
    shortTitle: "Dental Fillings",
    title: "Dental Fillings & Restorations",
    description: "Tooth-colored composite fillings that restore decayed or damaged teeth — blending seamlessly with your natural smile.",
    overview: "Dental fillings are one of the most common restorative procedures. At Vivek Dental, we use advanced tooth-colored composite materials that bond directly to your tooth, providing strong, aesthetic restorations. Dr. Vivek's expertise in conservative dentistry means preserving maximum healthy tooth structure while effectively treating decay.",
    whatToExpect: [
      "Examination and decay assessment",
      "Removal of decayed tooth material",
      "Shade matching for natural appearance",
      "Composite filling placement and shaping",
      "Bite adjustment and polishing",
    ],
    recovery: "Immediate — you can eat and drink right after the procedure. The filling is fully hardened before you leave the clinic.",
    faqs: [
      { question: "Are tooth-colored fillings as strong as silver fillings?", answer: "Modern composite fillings are highly durable and bond directly to tooth structure, often providing better support than traditional amalgam." },
      { question: "How long do fillings last?", answer: "Composite fillings typically last 5-10 years, depending on location and oral hygiene habits." },
      { question: "Is the procedure painful?", answer: "No — local anesthesia ensures complete comfort throughout the procedure." },
    ],
    metaTitle: "Dental Fillings in Hyderabad — Vivek Dental",
    metaDescription: "Tooth-colored dental fillings in Hyderabad. Natural-looking, durable restorations by Dr. Vivek. Conservative approach, maximum preservation.",
  },
  {
    slug: "dentures",
    shortTitle: "Dentures",
    title: "Complete & Partial Dentures",
    description: "Custom-crafted removable dentures — restoring your smile, speech, and ability to eat comfortably when multiple teeth are missing.",
    overview: "Dentures are removable replacements for missing teeth and surrounding tissues. Dr. Vivek offers both complete dentures (for patients missing all teeth) and cast partial dentures (when some natural teeth remain). Each denture is custom-fabricated for optimal fit, comfort, and natural appearance, restoring both function and aesthetics.",
    whatToExpect: [
      "Comprehensive oral examination",
      "Precise impressions and jaw measurements",
      "Wax try-in for fit and appearance approval",
      "Final denture fabrication and delivery",
      "Adjustment visits for perfect comfort",
    ],
    recovery: "An adjustment period of 2-4 weeks is normal as your mouth adapts. Follow-up visits ensure optimal fit and comfort.",
    faqs: [
      { question: "How long does it take to get dentures?", answer: "The process typically takes 3-5 appointments over 2-4 weeks for the best possible fit." },
      { question: "Can I eat normally with dentures?", answer: "Yes, after an adjustment period. Start with soft foods and gradually introduce harder items." },
      { question: "How do I care for dentures?", answer: "Remove and brush daily, soak overnight in denture cleanser, and visit regularly for check-ups." },
    ],
    metaTitle: "Dentures in Hyderabad — Vivek Dental",
    metaDescription: "Custom complete and partial dentures in Hyderabad. Natural-looking, comfortable fit by Dr. Vivek. Restore your smile today.",
  },
  {
    slug: "periodontal-treatment",
    shortTitle: "Gum Treatment",
    title: "Periodontal / Gum Treatment",
    description: "Advanced gum disease treatment including scaling, root planing, and periodontal flap surgery — protecting the foundation of your teeth.",
    overview: "Periodontal disease affects the gums and bone supporting your teeth, and if left untreated, can lead to tooth loss. Dr. Vivek provides comprehensive periodontal care — from deep cleaning (scaling and root planing) to advanced periodontal flap surgery. Early detection and treatment are key to saving your natural teeth and maintaining long-term oral health.",
    whatToExpect: [
      "Detailed periodontal examination and charting",
      "Deep scaling and root planing",
      "Flap surgery if indicated for advanced cases",
      "Post-treatment maintenance plan",
      "Regular follow-up for monitoring",
    ],
    recovery: "Mild gum tenderness for 2-3 days after deep cleaning. Surgical procedures may require 1-2 weeks of healing with prescribed medication.",
    faqs: [
      { question: "What are signs of gum disease?", answer: "Bleeding gums, persistent bad breath, receding gums, loose teeth, and swollen or tender gums are common signs." },
      { question: "Is gum treatment painful?", answer: "With local anesthesia, the procedure is comfortable. Post-treatment soreness is mild and manageable." },
      { question: "Can gum disease be reversed?", answer: "Early-stage gingivitis is fully reversible. Advanced periodontitis can be controlled and managed with proper treatment." },
    ],
    metaTitle: "Gum Treatment in Hyderabad — Vivek Dental",
    metaDescription: "Expert periodontal and gum treatment in Hyderabad. Scaling, root planing & flap surgery by Dr. Vivek. Protect your teeth foundation.",
  },
];